### ISSUE TITLE
Unzipping, then rezipping a workspace .zip file breaks it: it no longer opens

### ISSUE THREAD

**Issue by alexholcombe** [simbrain/simbrain#18]
At least on OSX 10.10, and I suspect generally, as @jyoshimi said he knows about this issue.

**Comment by jyoshimi** [comment]
Yeah, I just confirmed this.  To replicate:

1. Unzip `simulations/workspace/somLetters.zip`
2. Rezip to `simulations/workspace/somLetters2.zip`
3. Try top open ``simulations/workspace/somLetters.zip`

Null pointer exception:  ` at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106) at org.simbrain.workspace.WorkspaceSerializer.deserialize(WorkspaceSerializer.java:202) at org.simbrain.workspace.WorkspaceSerializer.deserialize(WorkspaceSerializer.java:159)`

So the issue is in [WorkspaceSerializer](https://github.com/simbrain/simbrain/blob/master/src/org/simbrain/workspace/WorkspaceSerializer.java)

I have notes from a few years back where I modified that class with some kind of hack to fix this, and when I get a chance will have a look and try to fix it, or at least post an update here.

- Jeff
