### ISSUE TITLE
Cannot open program in Linux Ubuntu

### ISSUE THREAD

**Issue by edaggett17** [simbrain/simbrain#48]
Hello All,
I am attempting to run my simulations on a more powerful machine which is equipped with the latest Ubuntu. When attempting to open 'Simbrain.jar' (utilizing Open JDK Java 8), the Simbrain logo appears for half a second then disappears. The program does not fully open and I am unable to open my simulations. 

I recall having a similar issue when I first tried utilizing the program on OS X. I don't believe I ever solved that issue and just ended up using the program on Windows. Has anyone experienced this issue and have a possible solution?

**Comment by jyoshimi** [comment]
Hi there.  Can you try running from the command line using "java -jar Simbrain.jar"? Then paste the console output here.  There should be an exception of some kind.  Or if it runs it might be something with executable jars on linux.

**Comment by edaggett17** [comment]
The following is the exception I received. 

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.NullPointerException
	at org.simbrain.workspace.updater.SynchronizingInvocationEvent$1.run(SynchronizingInvocationEvent.java:64)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.simbrain.workspace.gui.SimbrainDesktop.createScriptMenu(SimbrainDesktop.java:620)
	at org.simbrain.workspace.gui.SimbrainDesktop.createAndAttachMenus(SimbrainDesktop.java:603)
	at org.simbrain.workspace.gui.SimbrainDesktop.<init>(SimbrainDesktop.java:321)
	at org.simbrain.workspace.gui.SimbrainDesktop$8.run(SimbrainDesktop.java:1194)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at org.simbrain.workspace.updater.SynchronizingInvocationEvent$1$1.call(SynchronizingInvocationEvent.java:58)
	at org.simbrain.workspace.Workspace.syncRest(Workspace.java:599)
	at org.simbrain.workspace.Workspace.syncOnAllComponents(Workspace.java:577)
	at org.simbrain.workspace.updater.SynchronizingInvocationEvent$1.run(SynchronizingInvocationEvent.java:56)
	... 14 more

**Comment by jyoshimi** [comment]
This can happen if the Simbrain.jar file is moved.  Is Simbrain.jar in the same directory as the /scripts directory, the license, etc?   That is, if you run `ls` from the same place you ran `java -jar Simbrain.jar' do you get something like this?

`License.txt		Simbrain.jar		scripts
Readme.txt		docs			simulations
ReleaseNotes.txt	etc`

**Comment by edaggett17** [comment]
When I received the previously listed exception, all related files from the unzipped download were on the desktop. When I put them all into a file together, I receive the error "Error: Unable to access jar file". I am still very unfamiliar with JAVA (though attempting to learn), so I imagine this must be some remedial issue of file storage or unzipping the download file in an incorrect manner. Google searches have left me without resolution.

**Comment by jyoshimi** [comment]
I suspect you're right and it has to do with unzipping.  I suggest you re-download Simbrain, unzip to a separate folder that only contains the Simbrain stuff from my `ls` output above, then first try double clicking the jar, and then if that fails using `java -jar Simbrain.jar`.   Try this instead of re-arranging your previously unzipped stuff.  

If that fails, and if you have another machine, you could confirm the process works on it, then specify where the process differs on linux. If that still fails perhaps a brief screencast so I can see what you're doing?

**Comment by edaggett17** [comment]
Hello Jeff,
I now have 3.02 up and running. The issue was that I was not properly calling the directory in the command terminal prior to executing the .jar file. I'll chalk it up to getting familiar with Ubuntu/Linux. Thank you for your help and patience. 

- Eben
